### ISSUE TITLE
Define values.yaml for osm-seed Helm install

### ISSUE THREAD

**Issue by batpad** [hotosm/tf-azure-osm-seed#2]
We need to define all the `values` that the osm-seed helm chart needs, customized for the HOT osm-seed install.

These need to be added to the helm-osm-seed terraform file: https://github.com/hotosm/tf-azure-osm-seed/blob/main/deployment/terraform/resources/helm-osm-seed.tf#L12

Values can be added in three ways:

An initial, default set of values can be specified in a .yaml file and referenced with the `values` parameter, something like:

      values = [
        "${file("values.yaml")}"
      ]

Additional values, and things that need to come from the TF environment can be set using `set` parameters:

eg.

      set {
        name  = "cluster.enabled"
        value = "true"
      }

If a value contains sensitive information, we should use `set_sensitive` instead of `set`, so those values will not be displayed in logs, etc.

More documentation can be found here: https://registry.terraform.io/providers/hashicorp/helm/latest/docs/resources/release

@Rub21 do you think you could come up with an initial `values.yaml` file with configuration options to deploy on Azure, and then we can work on setting other variables from the environment, etc.

cc @geohacker

**Comment by batpad** [comment]
The only value we really needed to get osm-seed up and running was to set the `cloudProvider` value to `azure`.

We will probably want to customize this more, tweak some resource requirements, etc. so shall leave this issue open, but it's not a blocker to getting our basic setup going.

**Comment by batpad** [comment]
Realized we will need to set secrets for the emailer configuration. These are the values we will need: https://github.com/developmentseed/osm-seed/blob/develop/osm-seed/values.yaml#L111

We can wire this up to read from GH Secrets -> Terraform -> Helm tomorrow, and then @dakotabenjamin will let you know so you can add those so that we get email working.

**Comment by geohacker** [comment]
This is done!
